language: node_js
node_js:
- 11
- 8
script:
- npm run lint
- npm test
- npm run docs
deploy:
- provider: npm
  email: stefandesu@exo.pm
  api_key:
    secure: JNtCkfv6SVNfCt6sufQTg38LZgWa6dASKUEzKqiN5/ao8UJJh++p4Kd0PpTHKlzchVnw2fqmM2OczQVPFjG8cozd1VC6St9+Z5hPvkkylFzNcVltVAbj1VWl1vEI4t3I9pJWHgOsUTnbFW0JHw4lA07kSOt/t2OfduMl0AFiDrMwTKYh2bQfGDO3GYSCxNUxOpIUiP0d6YHLAsTmDzVCMD6X16fcn4IZdk6U05wbWuX7GixL5kEbcrkIHw/4mxoxAvjJVuotwO1pLoJ9L0PApDe6wMfO6ppYtXlLlJ9dqVOC1EmjqTlu+vAfXsqPGOLxz/njXNx8dPn/f5FUMjdHUcqiy1ajEbPHh9RaHYa+4Tiv5aBIxRM20MZl+Z239oOzlNXea7v4r72tYQ+KE+EEWtSU2fVD01lc5sBJhHvVifnEu4HFCibLk9xNqt7NwdXMRv+u+ADJUn5oV42LDdTFQsHMV35jnB18w1SIuPbBTWd/fFxdNg3/bJWOKUDB9HgzO2HPtmiw7gI/WaSIC/VCrlQKebt3mBzJ2VaI9ij4B8LiQOX8SP+0dworxJINeI1ZYJ82yGpT2D6TZFsHqSLJ1Fxkpf2iPZ7eKpw3g73m+j3OGouZFN4KAO4kt6yV3PoNPn/WUZSwrmfvwNOatl2ONwvAy6vUFExl1vEwJzPTvs4=
  on:
    npm: 8
    tags: true
    repo: gbv/jskos-tools
- provider: pages
  local-dir: jsdoc/build
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  on:
    node: 8
    tags: false
    branch: master
